require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VineMemesController do

  # This should return the minimal set of attributes required to create a valid
  # VineMeme. As you add validations to VineMeme, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "token" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VineMemesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all vine_memes as @vine_memes" do
      vine_meme = VineMeme.create! valid_attributes
      get :index, {}, valid_session
      assigns(:vine_memes).should eq([vine_meme])
    end
  end

  describe "GET show" do
    it "assigns the requested vine_meme as @vine_meme" do
      vine_meme = VineMeme.create! valid_attributes
      get :show, {:id => vine_meme.to_param}, valid_session
      assigns(:vine_meme).should eq(vine_meme)
    end
  end

  describe "GET new" do
    it "assigns a new vine_meme as @vine_meme" do
      get :new, {}, valid_session
      assigns(:vine_meme).should be_a_new(VineMeme)
    end
  end

  describe "GET edit" do
    it "assigns the requested vine_meme as @vine_meme" do
      vine_meme = VineMeme.create! valid_attributes
      get :edit, {:id => vine_meme.to_param}, valid_session
      assigns(:vine_meme).should eq(vine_meme)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new VineMeme" do
        expect {
          post :create, {:vine_meme => valid_attributes}, valid_session
        }.to change(VineMeme, :count).by(1)
      end

      it "assigns a newly created vine_meme as @vine_meme" do
        post :create, {:vine_meme => valid_attributes}, valid_session
        assigns(:vine_meme).should be_a(VineMeme)
        assigns(:vine_meme).should be_persisted
      end

      it "redirects to the created vine_meme" do
        post :create, {:vine_meme => valid_attributes}, valid_session
        response.should redirect_to(VineMeme.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved vine_meme as @vine_meme" do
        # Trigger the behavior that occurs when invalid params are submitted
        VineMeme.any_instance.stub(:save).and_return(false)
        post :create, {:vine_meme => { "token" => "invalid value" }}, valid_session
        assigns(:vine_meme).should be_a_new(VineMeme)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        VineMeme.any_instance.stub(:save).and_return(false)
        post :create, {:vine_meme => { "token" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested vine_meme" do
        vine_meme = VineMeme.create! valid_attributes
        # Assuming there are no other vine_memes in the database, this
        # specifies that the VineMeme created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        VineMeme.any_instance.should_receive(:update_attributes).with({ "token" => "MyString" })
        put :update, {:id => vine_meme.to_param, :vine_meme => { "token" => "MyString" }}, valid_session
      end

      it "assigns the requested vine_meme as @vine_meme" do
        vine_meme = VineMeme.create! valid_attributes
        put :update, {:id => vine_meme.to_param, :vine_meme => valid_attributes}, valid_session
        assigns(:vine_meme).should eq(vine_meme)
      end

      it "redirects to the vine_meme" do
        vine_meme = VineMeme.create! valid_attributes
        put :update, {:id => vine_meme.to_param, :vine_meme => valid_attributes}, valid_session
        response.should redirect_to(vine_meme)
      end
    end

    describe "with invalid params" do
      it "assigns the vine_meme as @vine_meme" do
        vine_meme = VineMeme.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VineMeme.any_instance.stub(:save).and_return(false)
        put :update, {:id => vine_meme.to_param, :vine_meme => { "token" => "invalid value" }}, valid_session
        assigns(:vine_meme).should eq(vine_meme)
      end

      it "re-renders the 'edit' template" do
        vine_meme = VineMeme.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VineMeme.any_instance.stub(:save).and_return(false)
        put :update, {:id => vine_meme.to_param, :vine_meme => { "token" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested vine_meme" do
      vine_meme = VineMeme.create! valid_attributes
      expect {
        delete :destroy, {:id => vine_meme.to_param}, valid_session
      }.to change(VineMeme, :count).by(-1)
    end

    it "redirects to the vine_memes list" do
      vine_meme = VineMeme.create! valid_attributes
      delete :destroy, {:id => vine_meme.to_param}, valid_session
      response.should redirect_to(vine_memes_url)
    end
  end

end
